# Site settings
title: Semantic Scribblings
email: csvoss [at] mit [dot] edu
description: > # this means to ignore newlines until "baseurl:"
  the blog of Chelsea Voss
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://csvoss.github.io" # the base hostname & protocol for your site
twitter_username: csvoss
github_username: csvoss
last_update: Feb 2018
exclude: [fonts/licenses.md]

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      comments: true
